name: sloco
description: A Dart cli tool to create translations for all Strings in your project
version: 0.0.2
homepage: https://www.bytabo.de

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.1.8

dependencies:
  args: ^2.3.0
  http: ^0.13.4
  dotenv: ^4.0.1
