name: sloco
description: A Dart cli tool to create translations for all Strings in your project
version: 0.0.7
homepage: https:/www.bytabo.de
repository: https://github.com/Nevoo/sloco
issue_tracker: https://github.com/Nevoo/sloco/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.9
  build_runner: ^2.4.6

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  dotenv: ^4.2.0

executables:
  sloco:
